name: CI Checks
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ci:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install npm modules
        run: npm ci
      - name: Build test module
        run: npm run build-for-testing-node
      - name: Run test
        run: npm test
      - name: Validate typings
        run: npm run validate-typings
      - name: Build for Electron
        run: npm run build-electron
